services:
  postgres-db:
    image: postgres:16-alpine
    container_name: healthcare-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: healthcare_dev_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d healthcare_dev_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  healthcare-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthcare-platform-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://postgres-db:5432/healthcare_dev_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgrespassword
      JWT_SECRET_KEY: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  postgres_data:
