package com.abi.claimbook.dm.mtdm;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import jakarta.persistence.CascadeType;

/**
* @author Narendhar
* @date 10-09-2016
* @description java class 
* @version 1.0
* 
*/

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

import org.hibernate.annotations.Filter;

/**
 * ModmTenantTb generated by hbm2java
 */
@Entity
@Table(name = "mtdm_tenant_tb")
public class Tenant implements java.io.Serializable {

	private static final long serialVersionUID = 1749834567343578019L;
	private Integer tenantId;
	private String tenantName;
	private String location;
	private String tenantUrl;
	private String status;
	private String tenantIdentifier;
	private String domain;
	private String email;
	private String additional_information;
	private String tenantCode;
	private String rohiniNumber;
	private String groupUrl;

	private boolean tenant;
	private String groupIdentifier;
	private boolean autoFtcEnabled;
	private String alias;
	private String groupName;
	private boolean queryColourSchemaEnabled;
	private boolean autoFetchTransactionEnabled;
	private String adminCode;
	private String hisAuthTokenExpiry;
	private Integer groupTenantId;
	private boolean inboxPurgingEnabled;
	private boolean miscPurgingEnabled;
	private boolean automationPurgingEnabled;
	private boolean notificationPurgingEnabled;
	private Integer inboxPreauthEmailPurgingDays;
	private Integer inboxClaimEmailPurgingDays;
	private Integer miscPreauthEmailPurgingDays;
	private Integer miscClaimEmailPurgingDays;
	private Integer preauthRpaPollingResponseClearanceDays;
	private Integer claimRpaPollingResponseClearanceDays;
	private Integer preauthNotificationClearanceDays;
	private Integer claimNotificationClearanceDays;
	private boolean corporateHisEnabled;
	private Date claimCreatedDate;
	private String hospitalShortName;
	private String mediAssistTenantIdentifier;
	private String hfrId;
	private String hcxParticipantCode;
	private String pollingTime;
	private boolean isSdmsProceed;
	private String claimbookSchemaIdentifier;
	private String unitCode;
	private String unitEmailId;
	private boolean mfaEnabled;
	private String apikey;
	private String credentials;
	private boolean m2m3Enabled;
	private boolean considerSubmitAsSave;
//	private boolean dischargeApprovedPolling;

	// @OneToOne(optional = false, mappedBy = "tenant", fetch = FetchType.LAZY,
	// cascade = CascadeType.ALL)
	// private MtdmTenantInformation tenantInformation;

	public Tenant() {
	}
//	@Column(name = "discharge_approved_polling", unique = true, nullable = false)
//	public boolean isDischargeApprovedPolling() {
//		return dischargeApprovedPolling;
//	}
//
//	public void setDischargeApprovedPolling(boolean dischargeApprovedPolling) {
//		this.dischargeApprovedPolling = dischargeApprovedPolling;
//	}

	public Tenant(Integer tenantId, String tenantName) {
		this.tenantId = tenantId;
		this.tenantName = tenantName;
	}

	public Tenant(Integer tenantId, String tenantName, String location, String tenantUrl, String status) {
		this.tenantId = tenantId;
		this.tenantName = tenantName;
		this.location = location;
		this.tenantUrl = tenantUrl;
		this.status = status;
	}

	public Tenant(Integer tenantId, String tenantName, String location, String tenantUrl, String status,
			String tenantIdentifier, String domain, String email, String additional_information) {
		super();
		this.tenantId = tenantId;
		this.tenantName = tenantName;
		this.location = location;
		this.tenantUrl = tenantUrl;
		this.status = status;
		this.tenantIdentifier = tenantIdentifier;
		this.domain = domain;
		this.email = email;
		this.additional_information = additional_information;
	}

	@Id
	@Column(name = "tenant_id", unique = true, nullable = false)
	public Integer getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(Integer tenantId) {
		this.tenantId = tenantId;
	}

	@Column(name = "tenant_name", nullable = false, length = 100)
	public String getTenantName() {
		return this.tenantName;
	}

	public void setTenantName(String tenantName) {
		this.tenantName = tenantName;
	}

	@Column(name = "location", length = 65)
	public String getLocation() {
		return this.location;
	}

	@Column(name = "is_query_colourschema_enabled")
	public boolean isQueryColourSchemaEnabled() {
		return queryColourSchemaEnabled;
	}

	public void setQueryColourSchemaEnabled(boolean queryColourSchemaEnabled) {
		this.queryColourSchemaEnabled = queryColourSchemaEnabled;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "tenant_url")
	public String getTenantUrl() {
		return this.tenantUrl;
	}

	public void setTenantUrl(String tenantUrl) {
		this.tenantUrl = tenantUrl;
	}

	@Column(name = "status", length = 65)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "tenant_identifier")
	public String getTenantIdentifier() {
		return tenantIdentifier;
	}

	public void setTenantIdentifier(String tenantIdentifier) {
		this.tenantIdentifier = tenantIdentifier;
	}

	@Column(name = "domain")
	public String getDomain() {
		return domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "email")
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "additional_information")
	public String getAdditional_information() {
		return additional_information;
	}

	public void setAdditional_information(String additional_information) {
		this.additional_information = additional_information;
	}

	@Column(name = "tenant_code")
	public String getTenantCode() {
		return tenantCode;
	}

	public void setTenantCode(String tenantCode) {
		this.tenantCode = tenantCode;
	}

	@Column(name = "rohini_number")
	public String getRohiniNumber() {
		return rohiniNumber;
	}

	public void setRohiniNumber(String rohiniNumber) {
		this.rohiniNumber = rohiniNumber;
	}

//    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tenant", cascade = CascadeType.ALL)
//    @Where(clause = "functionality = 'PREAUTH'")
//    public List<MtdmTenantEmail> getPreauthEmailList() {
//	return preauthEmailList;
//    }
	// changed by raj

//    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tenant", cascade = CascadeType.ALL)
//    @Where(clause = "functionality = 'CLAIMS'")
//    public List<MtdmTenantEmail> getClaimEmailList() {
//	return claimEmailList;
//    }
	// changed by raj

	@Column(name = "is_tenant")
	public boolean isTenant() {
		return tenant;
	}

	public void setTenant(boolean tenant) {
		this.tenant = tenant;
	}

	@Column(name = "group_identifier")
	public String getGroupIdentifier() {
		return groupIdentifier;
	}

	public void setGroupIdentifier(String groupIdentifier) {
		this.groupIdentifier = groupIdentifier;
	}

	@Column(name = "group_url")
	public String getGroupUrl() {
		return groupUrl;
	}

	public void setGroupUrl(String groupUrl) {
		this.groupUrl = groupUrl;
	}

	@Column(name = "auto_ftc_enabled")
	public boolean isAutoFtcEnabled() {
		return autoFtcEnabled;
	}

	public void setAutoFtcEnabled(boolean autoFtcEnabled) {
		this.autoFtcEnabled = autoFtcEnabled;
	}

	@Column(name = "alias")
	public String getAlias() {
		return alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Column(name = "group_name")
	public String getGroupName() {
		return groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "auto_fetch_transaction_enabled")
	public boolean isAutoFetchTransactionEnabled() {
		return autoFetchTransactionEnabled;
	}

	public void setAutoFetchTransactionEnabled(boolean autoFetchTransactionEnabled) {
		this.autoFetchTransactionEnabled = autoFetchTransactionEnabled;
	}

	@Column(name = "admin_code")
	public String getAdminCode() {
		return adminCode;
	}

	public void setAdminCode(String adminCode) {
		this.adminCode = adminCode;
	}

	@Column(name = "inbox_purging_enabled")
	public boolean isInboxPurgingEnabled() {
		return inboxPurgingEnabled;
	}

	public void setInboxPurgingEnabled(boolean inboxPurgingEnabled) {
		this.inboxPurgingEnabled = inboxPurgingEnabled;
	}

	@Column(name = "misc_purging_enabled")
	public boolean isMiscPurgingEnabled() {
		return miscPurgingEnabled;
	}

	public void setMiscPurgingEnabled(boolean miscPurgingEnabled) {
		this.miscPurgingEnabled = miscPurgingEnabled;
	}

	@Column(name = "automation_purging_enabled")
	public boolean isAutomationPurgingEnabled() {
		return automationPurgingEnabled;
	}

	public void setAutomationPurgingEnabled(boolean automationPurgingEnabled) {
		this.automationPurgingEnabled = automationPurgingEnabled;
	}

	@Column(name = "notification_purging_enabled")
	public boolean isNotificationPurgingEnabled() {
		return notificationPurgingEnabled;
	}

	public void setNotificationPurgingEnabled(boolean notificationPurgingEnabled) {
		this.notificationPurgingEnabled = notificationPurgingEnabled;
	}

	@Column(name = "his_auth_token_expiry")
	public String getHisAuthTokenExpiry() {
		return hisAuthTokenExpiry;
	}

	public void setHisAuthTokenExpiry(String hisAuthTokenExpiry) {
		this.hisAuthTokenExpiry = hisAuthTokenExpiry;
	}

	@Column(name = "group_tenant_id")
	public Integer getGroupTenantId() {
		return groupTenantId;
	}

	public void setGroupTenantId(Integer groupTenantId) {
		this.groupTenantId = groupTenantId;
	}

	@Column(name = "inbox_preauth_email_purging_days")
	public Integer getInboxPreauthEmailPurgingDays() {
		return inboxPreauthEmailPurgingDays;
	}

	public void setInboxPreauthEmailPurgingDays(Integer inboxPreauthEmailPurgingDays) {
		this.inboxPreauthEmailPurgingDays = inboxPreauthEmailPurgingDays;
	}

	@Column(name = "inbox_claim_email_purging_days")
	public Integer getInboxClaimEmailPurgingDays() {
		return inboxClaimEmailPurgingDays;
	}

	public void setInboxClaimEmailPurgingDays(Integer inboxClaimEmailPurgingDays) {
		this.inboxClaimEmailPurgingDays = inboxClaimEmailPurgingDays;
	}

	@Column(name = "misc_preauth_email_purging_days")
	public Integer getMiscPreauthEmailPurgingDays() {
		return miscPreauthEmailPurgingDays;
	}

	public void setMiscPreauthEmailPurgingDays(Integer miscPreauthEmailPurgingDays) {
		this.miscPreauthEmailPurgingDays = miscPreauthEmailPurgingDays;
	}

	@Column(name = "misc_claim_email_purging_days")
	public Integer getMiscClaimEmailPurgingDays() {
		return miscClaimEmailPurgingDays;
	}

	public void setMiscClaimEmailPurgingDays(Integer miscClaimEmailPurgingDays) {
		this.miscClaimEmailPurgingDays = miscClaimEmailPurgingDays;
	}

	@Column(name = "preauth_rpa_polling_response_clearance_days")
	public Integer getPreauthRpaPollingResponseClearanceDays() {
		return preauthRpaPollingResponseClearanceDays;
	}

	public void setPreauthRpaPollingResponseClearanceDays(Integer preauthRpaPollingResponseClearanceDays) {
		this.preauthRpaPollingResponseClearanceDays = preauthRpaPollingResponseClearanceDays;
	}

	@Column(name = "claim_rpa_polling_response_clearance_days")
	public Integer getClaimRpaPollingResponseClearanceDays() {
		return claimRpaPollingResponseClearanceDays;
	}

	public void setClaimRpaPollingResponseClearanceDays(Integer claimRpaPollingResponseClearanceDays) {
		this.claimRpaPollingResponseClearanceDays = claimRpaPollingResponseClearanceDays;
	}

	@Column(name = "preauth_notification_clearance_days")
	public Integer getPreauthNotificationClearanceDays() {
		return preauthNotificationClearanceDays;
	}

	public void setPreauthNotificationClearanceDays(Integer preauthNotificationClearanceDays) {
		this.preauthNotificationClearanceDays = preauthNotificationClearanceDays;
	}

	@Column(name = "claim_notification_clearance_days")
	public Integer getClaimNotificationClearanceDays() {
		return claimNotificationClearanceDays;
	}

	public void setClaimNotificationClearanceDays(Integer claimNotificationClearanceDays) {
		this.claimNotificationClearanceDays = claimNotificationClearanceDays;
	}

	@Column(name = "corporate_his_enabled")
	public boolean isCorporateHisEnabled() {
		return corporateHisEnabled;
	}

	public void setCorporateHisEnabled(boolean corporateHisEnabled) {
		this.corporateHisEnabled = corporateHisEnabled;
	}

	@Column(name = "gcd_start_date")
	@Temporal(TemporalType.DATE)
	public Date getClaimCreatedDate() {
		return claimCreatedDate;
	}

	public void setClaimCreatedDate(Date claimCreatedDate) {
		this.claimCreatedDate = claimCreatedDate;
	}

	@Column(name = "hospital_short_name")
	public String getHospitalShortName() {
		return hospitalShortName;
	}

	public void setHospitalShortName(String hospitalShortName) {
		this.hospitalShortName = hospitalShortName;
	}

	@Column(name = "hfr_id")
	public String getHfrId() {
		return hfrId;
	}

	public void setHfrId(String hfrId) {
		this.hfrId = hfrId;
	}

	@Column(name = "mediassist_tenant_identifier")
	public String getMediAssistTenantIdentifier() {
		return mediAssistTenantIdentifier;
	}

	public void setMediAssistTenantIdentifier(String mediAssistTenantIdentifier) {
		this.mediAssistTenantIdentifier = mediAssistTenantIdentifier;
	}

	// public MtdmTenantInformation getTenantInformation() {
	// return tenantInformation;
	// }
	//
	// public void setTenantInformation(MtdmTenantInformation tenantInformation)
	// {
	// this.tenantInformation = tenantInformation;
	// }
	@Column(name = "hcx_participant_code")
	public String getHcxParticipantCode() {
		return hcxParticipantCode;
	}

	public void setHcxParticipantCode(String hcxParticipantCode) {
		this.hcxParticipantCode = hcxParticipantCode;
	}

	@Column(name = "polling_time")
	public String getPollingTime() {
		return pollingTime;
	}

	public void setPollingTime(String pollingTime) {
		this.pollingTime = pollingTime;
	}

	@Column(name = "sdms_enable")
	public boolean isSdmsProceed() {
		return isSdmsProceed;
	}

	public void setSdmsProceed(boolean isSdmsProceed) {
		this.isSdmsProceed = isSdmsProceed;
	}

	@Column(name = "sche_name")
	public String getClaimbookSchemaIdentifier() {
		return claimbookSchemaIdentifier;
	}

	public void setClaimbookSchemaIdentifier(String claimbookSchemaIdentifier) {
		this.claimbookSchemaIdentifier = claimbookSchemaIdentifier;
	}

	@Column(name = "unit_code")
	public String getUnitCode() {
		return unitCode;
	}

	public void setUnitCode(String unitCode) {
		this.unitCode = unitCode;
	}

	@Column(name = "unit_email_id")
	public String getUnitEmailId() {
		return unitEmailId;
	}

	public void setUnitEmailId(String unitEmailId) {
		this.unitEmailId = unitEmailId;
	}

	@Column(name = "mfa_enabled")
	public boolean isMfaEnabled() {
		return mfaEnabled;
	}

	public void setMfaEnabled(boolean mfaEnabled) {
		this.mfaEnabled = mfaEnabled;
	}

	@Column(name = "credentials")
	public String getCredentials() {
		return credentials;
	}

	public void setCredentials(String credentials) {
		this.credentials = credentials;
	}

	@Column(name = "api_key")
	public String getApikey() {
		return apikey;
	}

	public void setApikey(String apikey) {
		this.apikey = apikey;
	}

	@Column(name = "m2m3_enabled")
	public boolean isM2m3Enabled() {
		return m2m3Enabled;
	}

	public void setM2m3Enabled(boolean m2m3Enabled) {
		this.m2m3Enabled = m2m3Enabled;
	}

	@Column(name = "consider_submit_as_save")
	public boolean isConsiderSubmitAsSave() {
		return considerSubmitAsSave;
	}

	public void setConsiderSubmitAsSave(boolean considerSubmitAsSave) {
		this.considerSubmitAsSave = considerSubmitAsSave;
	}
}
