package com.abi.claimbook.dm.oltp;
/**
 * @author Narendhar
 * @date 29-09-2016
 * @description used for Entity
 * @version 1.0
 * 
 */
// default package

// Generated Sep 27, 2016 11:53:18 AM by Hibernate Tools 5.1.0.Alpha1

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import lombok.Data;

/**
 * OltpProviderOrganization generated by hbm2java
 */
@Data
@Table(name = "oltp_provider_organization")
public class ProviderOrganization implements java.io.Serializable {

	private static final long serialVersionUID = -323831697130272706L;
	@Id
	@SequenceGenerator(name = "oltp_provider_organization_provider_id_seq", sequenceName = "oltp_provider_organization_provider_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "oltp_provider_organization_provider_id_seq")
	@Column(name = "provider_id", unique = true, nullable = false)
	private Integer providerId;

	@Column(name = "is_active")
	private boolean active;

	@Column(name = "mtdm_master_provider_id")
	private Integer masterproviderId;

	@Column(name = "gst")
	private String gst;

	@Column(name = "tan")
	private String tan;

	@Column(name = "pan")
	private String pan;

	@Column(name = "deleted")
	private boolean deleted;

	@Column(name = "insurance_display_name")
	private String insuranceDisplayName;

	@Column(name = "his_insurance_name")
	private String hisInsuranceName;

	@Column(name = "hcx_insurance_organization_enabled")
	private boolean isHCXInsuranceOrganizationEnabled;

	@Column(name = "is_corporate_enabled")
	private boolean isCorporateEnabled;

}
