spring:
  application:
    name: enterprise-healthcare-platform
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
    banner-mode: console

server:
  port: 8080
  servlet:
    context-path: /api
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,loggers
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

app:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      access-token-expiration-ms: 900000 # 15 mins
      refresh-token-expiration-ms: 604800000 # 7 days
      issuer: enterprise-healthcare-auth-server

resilience4j:
  circuitbreaker:
    instances:
      externalClaimsService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
  retry:
    instances:
      externalClaimsService:
        maxAttempts: 3
        waitDuration: 2000ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
